CREATE TABLE IF NOT EXISTS wegvakken (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    bron_id VARCHAR(160) NULL,
    objectid INT NULL,
    wvk_id DECIMAL(18, 0) NULL,
    wvk_begdat DATETIME NULL,
    wegnummer VARCHAR(32) NULL,
    wegnr_hmp VARCHAR(32) NULL,
    wegnr_aw VARCHAR(32) NULL,
    routeltr VARCHAR(8) NULL,
    routenr INT NULL,
    wegdeelltr VARCHAR(16) NULL,
    wegtype VARCHAR(16) NULL,
    wgtype_oms VARCHAR(120) NULL,
    stt_naam VARCHAR(255) NULL,
    gme_id INT NULL,
    gme_naam VARCHAR(160) NULL,
    wpsnaam VARCHAR(160) NULL,
    wegbehcode VARCHAR(64) NULL,
    wegbehnaam VARCHAR(255) NULL,
    wegbehsrt VARCHAR(120) NULL,
    dienstnaam VARCHAR(160) NULL,
    distrnaam VARCHAR(160) NULL,
    beginkm DOUBLE NULL,
    eindkm DOUBLE NULL,
    begafstand INT NULL,
    endafstand INT NULL,
    geometry_geojson LONGTEXT NULL,
    properties_json LONGTEXT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY wegvakken_bron_id_unique_idx (bron_id),
    KEY wegvakken_wvk_idx (wvk_id, wvk_begdat),
    KEY wegvakken_road_idx (wegnr_hmp, routeltr, routenr, wegnummer, wegnr_aw),
    KEY wegvakken_place_idx (wpsnaam, gme_naam)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS hectopunten (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    bron_id VARCHAR(160) NULL,
    objectid INT NULL,
    wvk_id DECIMAL(18, 0) NULL,
    wvk_begdat DATETIME NULL,
    afstand INT NULL,
    hectometrering INT NULL,
    hectometer DECIMAL(8, 3) NULL,
    zijde VARCHAR(16) NULL,
    hectoletter VARCHAR(16) NULL,
    longitude DECIMAL(10, 7) NULL,
    latitude DECIMAL(10, 7) NULL,
    geometry_geojson LONGTEXT NULL,
    properties_json LONGTEXT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY hectopunten_bron_id_unique_idx (bron_id),
    KEY hectopunten_wvk_idx (wvk_id, wvk_begdat),
    KEY hectopunten_search_idx (hectometrering, zijde, hectoletter),
    KEY hectopunten_location_idx (longitude, latitude)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
